name: korean_words
description: A new Flutter package project.
version: 1.0.1
author: PlatiB <platib85@gmail.com>
homepage: https://github.com/PlatiB/korean_words

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter